### ISSUE TITLE
Program doesn't compile in 32 bit processor

### ISSUE THREAD

**Issue by ashishmainali** [pr0f3ss/SHA512#1]
error: expected unqualified-id before ‘__int128’
 typedef unsigned __int128 uint128;

**Comment by mallardtheduck** [comment]
The best way to resolve this is to remove the `uint128` typedef altogether and replace the `SHA512::appendLen` method with the "standard" 64x64 multiplication algorithm as follows:

```
void SHA512::appendLen(uint64 mLen, uint64 mp, uint64& lo, uint64& hi) {
	uint64_t u1 = (mLen & 0xffffffff);
	uint64_t v1 = (mp & 0xffffffff);
	uint64_t t = (u1 * v1);
	uint64_t w3 = (t & 0xffffffff);
	uint64_t k = (t >> 32);

	mLen >>= 32;
	t = (mLen * v1) + k;
	k = (t & 0xffffffff);
	uint64_t w1 = (t >> 32);

	mp >>= 32;
	t = (u1 * mp) + k;
	k = (t >> 32);

	hi = (mLen * mp) + w1 + k;
	lo = (t << 32) + w3;
}
```

**Comment by ashishmainali** [comment]
Thanks for your response. 
    On Thursday, September 24, 2020, 10:50:51 AM CDT, mallardtheduck <notifications@github.com> wrote:  
 
 


The best way to resolve this is to remove the uint128 typedef altogether and replace the SHA512::appendLen method with the "standard" 64x64 multiplication algorithm as follows:
void SHA512::appendLen(uint64 mLen, uint64 mp, uint64& lo, uint64& hi) {
	uint64_t u1 = (mLen & 0xffffffff);
	uint64_t v1 = (mp & 0xffffffff);
	uint64_t t = (u1 * v1);
	uint64_t w3 = (t & 0xffffffff);
	uint64_t k = (t >> 32);

	mLen >>= 32;
	t = (mLen * v1) + k;
	k = (t & 0xffffffff);
	uint64_t w1 = (t >> 32);

	mp >>= 32;
	t = (u1 * mp) + k;
	k = (t >> 32);

	hi = (mLen * mp) + w1 + k;
	lo = (t << 32) + w3;
}

**Comment by pr0f3ss** [comment]
This is fixed now. However, the implementation now only can take up messages of size at most size_t.
