### ISSUE TITLE
Incorrect output when any of the 64-bit words begins with a zero nybble

### ISSUE THREAD

**Issue by mallardtheduck** [pr0f3ss/SHA512#2]
As the string conversion is not zero-padded, in the case that any of the 64-bit words of the hash starts with a zero, the output will be incorrect (too short).

To fix this, replace the line:

    ss << std::hex << h[i];

with:

    ss << std::hex << std::setw(16) << std::setfill('0') << h[i];

In the `SHA512::digest` method.

**Comment by pr0f3ss** [comment]
This is fixed now. Thanks for the heads up!
